### ISSUE TITLE
Differences & Purposes

### ISSUE THREAD

**Issue by ghost** [CindyLinz/JS-aes#1]
@CindyLinz I know that this repository has been inactive for quite a while, but I was wondering if you would be willing to clarify some things for me. I'm trying to look into AES, so I'm very new to this.

- What distinguishes the three methods used from one another (is there one you suggest using)?
- I noticed that the key was in `test.js`. Why did you not let the user come up with an input?
- What is the purpose of the `block number`?

Is there anything else I should know about your project?

**Comment by CindyLinz** [comment]
These methods use the same algorithm and generate the same result. The difference of them are different implementation with different running speed. You can use the test page to check the different running time of them. `asm.js` should be the fastest one if your browser supports it.

The original purpose of this project is a practice for me. I didn't think about making it a library for practical use. That's why I just type a fixed key in `test.js`. You can change to anything else if you like~

What do you mean `block number`? Are those numbers that I marked as `rcon`, `fsbox`, ...? They're internal numbers specified by AES.

**Comment by ghost** [comment]
I think that's what I mean for `block number`, but I'm sure that it is an option on the HTML page.

**Comment by ghost** [comment]
Just only more thing from me:

Based on the numbers used in the algorithm, do you think it would be possible to implement a custom PIN number input that _slightly_ alters the process? If so, where in the script?

It's a hard question, but if you don't know then that is totally okay. I'm just trying to implement something with a code for an encryption project I'm working on.

**Comment by CindyLinz** [comment]
The numbers are the key to the security. If we change the numbers, we can still implement an algorithm with consistent encryption and decryption. Though it would be probably easier to break. And I can't answer the reason.
